### ISSUE TITLE
最新版沒有把漢語拼音字元包含進去

### ISSUE THREAD

**Issue by ghost** [cjkvi/HanaMinAFDKO#1]
原版是含有漢語拼音字元的。

**Comment by kawabata** [comment]
This version of HanaMin font is mainly focused on Hanzi and related scripts, not to include latin or other western scripts.  Let me know if you have any reasonable rationale to include pinyin characters, not using other fonts for them, and I may re-consider to include extended Latin blocks of Unicode that includes pinyin characters.

**Comment by kawabata** [comment]
Now HanaMinAX.otf includes all pinyin characters.  If you still want HanaMinA.otf to include all pinyin characters, please let me know.
