### ISSUE TITLE
The width of English letters are not correct

### ISSUE THREAD

**Issue by subdudu** [cjkvi/HanaMinAFDKO#2]
The width of English letters are too wide, as wide as CJK characters. And if a character is not contained in the font, I think it is better to show a visible sign (a box for example)  than a wide space, because it is confusing to see a wide space.
![2018-02-02 09-22-30](https://user-images.githubusercontent.com/859949/35715813-ba083354-080f-11e8-8003-e865109aa88a.png)

**Comment by kawabata** [comment]
The new release (https://github.com/cjkvi/HanaMinAFDKO/releases/tag/8.021)
tries to half the width for some glyphs.  I apprecite if you could check if it works.
